const actionTypes = Object.freeze({
  GET_PRODUCT_ALL: "GET_PRODUCT_ALL",
  ADD_CART_ITEM: "ADD_CART_ITEM",
  REMOVE_CART_SUCCESS: "REMOVE_CART_SUCCESS",
  REMOVE_CART_FAILURE: "REMOVE_CART_FAILURE",
  UPDATE_CART_ITEM: "UPDATE_CART_ITEM",
  ORDER_PRODUCT: "ORDER_PRODUCT",
});

export default actionTypes;
